
  ALTER PROC insertTempTable
    AS
    BEGIN
      BEGIN TRY
        INSERT INTO TemporaryTable VALUES (	'A dive into Data Quality Services'	,	'Steve'	,	'Simon'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'A Dynamic World Demands Dynamic SQL'	,	'Jeremiah'	,	'Peschka'	,	'Intermediate'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'A Dynamic World Demands Dynamic SQL'	,	'Jeremiah'	,	'Peschka'	,	'Intermediate'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'Absolute Introductory Session on SQL Server 2014 In-Memory Optimized Databases (Hekaton)'	,	'Kevin'	,	'Goff'	,	'Beginner'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'AlwaysOn: Improve reliability and reporting performance with one cool tech'	,	'Chris'	,	'Seferlis'	,	'Beginner'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'An introduction to Data Mining'	,	'Steve'	,	'Simon'	,	'Intermediate'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'An Introduction to Database Design'	,	'Mohammad'	,	'Yusuf'	,	'Beginner'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Autogenerating a process data warehouse'	,	'Kennie'	,	'Pontoppidan'	,	'Advanced'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Automate your daily checklist with PBM and CMS'	,	'John'	,	'Sterrett'	,	'Intermediate'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'Automated Installing and Configuration of SQL2014/SQL2012 AlwaysOn Across Multiple Datacenters'	,	'Thomas'	,	'Grohser'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Automated Installing and Configuration of SQL2014/SQL2012 AlwaysOn Across Multiple Datacenters'	,	'Thomas'	,	'Grohser'	,	'Intermediate'	,	'kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'Automating Execution Plan Analysis'	,	'Joe'	,	'Chang'	,	'Advanced'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'Automating Execution Plan Analysis'	,	'Joe'	,	'Chang'	,	'Advanced'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Automating SQL Server using PowerShell'	,	'Michael'	,	'Wharton'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Balanced Scorecards using SSRS'	,	'Sunil'	,	'Kadimdiwan'	,	'Intermediate'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'Baselines and Performance Monitoring with PAL'	,	'Mike'	,	'Walsh'	,	'Beginner'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Basic Database Design'	,	'John'	,	'Miner'	,	'Beginner'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Basic Database Programming'	,	'John'	,	'Miner'	,	'Beginner'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'Become a BI Independent Consultant!'	,	'James'	,	'Serra'	,	'Beginner'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'Best Practices Document'	,	'Paresh'	,	'Motiwala'	,	'Intermediate'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'Best Practices for Efficient SSRS Report Creation'	,	'Mickey'	,	'Stuewe'	,	'Beginner'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Biggest Loser: Database Edition'	,	'John'	,	'Miner'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Building a BI Solution in the Cloud'	,	'Stacia'	,	'Misner'	,	'Intermediate'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'Building an Effective Data Warehouse Architecture'	,	'James'	,	'Serra'	,	'Beginner'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Building an Effective Data Warehouse Architecture with the cloud and MPP'	,	'James'	,	'Serra'	,	'Beginner'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Bulk load and minimal logged inserts'	,	'David'	,	'Peter Hansen'	,	'Advanced'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Business Analytics with SQL Server & Power Map:Everything you want to know but were afraid to ask'	,	'Steve'	,	'Simon'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Challenges to designing financial warehouses, lessons learnt'	,	'Steve'	,	'Simon'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Change Data Capture in SQL Server 2008/2012'	,	'Kevin'	,	'Goff'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Changing Your Habits to Improve the Performance of Your T-SQL'	,	'Mickey'	,	'Stuewe'	,	'Beginner'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'Clusters Your Way: #SANLess Clusters for Physical, Virtual, and Cloud Environments'	,	'Allan'	,	'Hirt and SIOS Technology'	,	'Beginner'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'Clusters Your Way: #SANLess Clusters for Physical, Virtual, and Cloud Environments'	,	'Allan'	,	'Hirt'	,	'Non-Technical'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'Coffee Break'	,	'SQLSatruday'	,	'364'	,	'Non-Technical'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'Creating A Performance Health Repository - using MDW'	,	'Robert'	,	'Pearl'	,	'Beginner'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'Creating efficient and effective SSRS BI Solutions'	,	'Steve'	,	'Simon'	,	'Intermediate'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'Creating efficient and effective SSRS BI Solutions'	,	'Steve'	,	'Simon'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Data Partitioning'	,	'John'	,	'Flannery'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Data Tier Application Testing with NUnit and Distributed Replay'	,	'John'	,	'Flannery'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Database design for mere developers'	,	'Steve'	,	'Simon'	,	'Intermediate'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'Database design for mere developers'	,	'Steve'	,	'Simon'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Database Design: Solving Problems Before they Start!'	,	'Edward'	,	'Pollack'	,	'Beginner'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Database Modeling and Design'	,	'Mohammad'	,	'Yusuf'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Database Virtualization and Drinking out of the Fire Hose'	,	'Michael'	,	'Corey'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'DAX and the tabular model'	,	'Steve'	,	'Simon'	,	'Intermediate'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'DBA FOR DUMMIES'	,	'Robert'	,	'Pearl'	,	'Beginner'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'Dealing With Difficult People'	,	'Gigi'	,	'Bell'	,	'Beginner'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'Development Lifecycle with SQL Server Data Tools and DACFx'	,	'John'	,	'Flannery'	,	'Intermediate'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'Did You Vote Today? A DBAs Guide to Cluster Quorum'	,	'Allan'	,	'Hirt'	,	'Advanced'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'Dimensional Modeling Design Patterns: Beyond Basics'	,	'Jason'	,	'Horner'	,	'Intermediate'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'Dimensional Modeling Design Patterns: Beyond Basics'	,	'Jason'	,	'Horner'	,	'Intermediate'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'Diving Into Query Execution Plans'	,	'Edward'	,	'Pollack'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Dynamic SQL: Writing Efficient Queries on the Fly'	,	'Edward'	,	'Pollack'	,	'Beginner'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'Easy Architecture Design for HA and DR'	,	'Brent'	,	'Ozar'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Enhancing your career: Building your personal brand'	,	'James'	,	'Serra'	,	'Beginner'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Establishing a SLA'	,	'Thomas'	,	'Grohser'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'ETL not ELT! Common mistakes and misconceptions about SSIS'	,	'Paul'	,	'Rizza'	,	'Advanced'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'Event Kickoff and Networking'	,	'SQLSaturday'	,	'364'	,	'Non-Technical'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Execution Plans: What Can You Do With Them?'	,	'Grant'	,	'Fritchey'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Faster, Better Decisions with Self Service Business Analytics'	,	'Sayed'	,	'Saeed'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Full Text Indexing Basics'	,	'John'	,	'Miner'	,	'Beginner'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'Get your Mining Model Predictions out to all'	,	'Steve'	,	'Simon'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Getting a job with Microsoft'	,	'Paul'	,	'Rizza'	,	'Non-Technical'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Graph Databases for SQL Server Professionals'	,	'Stéphane'	,	'Fréchette'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Hacking Exposé - Using SSL to Protect SQL Connections'	,	'Chris'	,	'Bell'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Hacking the SSIS 2012 Catalog'	,	'Andy'	,	'Leonard'	,	'Beginner'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'Hidden in plain sight: master your tools'	,	'Varsham'	,	'Papikian'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Highly Available SQL Server in Windows Azure IaaS'	,	'David'	,	'Bermingham'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'How to Make a LOT More Money as a Consultant'	,	'James'	,	'Serra'	,	'Beginner'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'How to Think Like the Engine'	,	'Brent'	,	'Ozar'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Hybrid Cloud Scenarios with SQL Server 2014'	,	'George'	,	'Walters'	,	'Intermediate'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'Hybrid Solutions: The Future of SQL Server Disaster Recovery'	,	'Allan'	,	'Hirt'	,	'Intermediate'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'Implementing Data Warehouse Patterns with the Microsoft BI Tools'	,	'Kevin'	,	'Goff'	,	'Intermediate'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'Inroduction to Triggers'	,	'Jack'	,	'Corbett'	,	'Beginner'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'Integrating Reporting Services with SharePoint'	,	'Kevin'	,	'Goff'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Integration Services (SSIS) for the DBA'	,	'David'	,	'Peter Hansen'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Introducing Power BI'	,	'Stacia'	,	'Misner'	,	'Beginner'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Introduction to Database Recovery'	,	'John'	,	'Flannery'	,	'Beginner'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Introduction to High Availability with SQL Server'	,	'John'	,	'Sterrett'	,	'Beginner'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Introduction to Powershell for DBA'	,	'John'	,	'Sterrett'	,	'Beginner'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Introduction to SQL Server - Part 1'	,	'Brandon'	,	'Leach'	,	'Beginner'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Introduction to SQL Server - Part 2'	,	'Brandon'	,	'Leach'	,	'Beginner'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Is That A Failover Cluster On Your Laptop/Desktop?'	,	'Allan'	,	'Hirt'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Leaving the Windows Open'	,	'Jeremiah'	,	'Peschka'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Lunch Break'	,	'SQLSaturday'	,	'364'	,	'Non-Technical'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Lunchtime Keynote'	,	'SQLSaturday'	,	'364'	,	'Non-Technical'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Master Data Services Best Practices'	,	'Steve'	,	'Simon'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Master Data Services Disaster Recovery'	,	'Steve'	,	'Simon'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Mind your language!! Cursors are a dirty word'	,	'Steve'	,	'Simon'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Modern Data Warehousing'	,	'James'	,	'Serra'	,	'Beginner'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Monitoring Server health via Reporting Services dashboards'	,	'Steve'	,	'Simon'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Monitoring SQL Server using Extended Events'	,	'Hilary'	,	'Cotter'	,	'Beginner'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Multidimensional vs Tabular - May the Best Model Win'	,	'Stacia'	,	'Misner'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Murder They Wrote'	,	'Jason'	,	'Brimhall'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Never Have to Say "Mayday!!!" Again'	,	'Mike'	,	'Walsh'	,	'Beginner'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Now you see it! Now you don’t! Conjuring many reports utilizing only one SSRS report.'	,	'Steve'	,	'Simon'	,	'Intermediate'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Optimal Infrastructure Strategies for Cisco UCS, Nexus and SQL Server'	,	'Kevin'	,	'Schenega'	,	'Non-Technical'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'Optimizing Protected Indexes'	,	'Chris'	,	'Bell'	,	'Intermediate'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'Partitioning as a design pattern'	,	'Kennie'	,	'Pontoppidan'	,	'Advanced'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'Power BI Components in Microsofts Self-Service BI Suite'	,	'Todd'	,	'Chittenden'	,	'Beginner'	,	'New York'	);
        INSERT INTO TemporaryTable VALUES (	'Power to the people!!'	,	'Steve'	,	'Simon'	,	'Intermediate'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'PowerShell Basics for SQLServer'	,	'Michael'	,	'Wharton'	,	'Beginner'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'PowerShell for the Reluctant DBA / Developer'	,	'Jason'	,	'Horner'	,	'Beginner'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'Prevent Recovery Amnesia – Forget the Backups'	,	'Chris'	,	'Bell'	,	'Beginner'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'Query Optimization Crash Course'	,	'Edward'	,	'Pollack'	,	'Beginner'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'Rapid Application Development with Master Data Services'	,	'Steve'	,	'Simon'	,	'Intermediate'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'Recovery and Backup for Beginners'	,	'Mike'	,	'Hillwig'	,	'Beginner'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'Reduce, Reuse, Recycle: Automating Your BI Framework'	,	'Stacia'	,	'Misner'	,	'Intermediate'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'Replicaton Technologies'	,	'Hilary'	,	'Cotter'	,	'Advanced'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'Reporting Services for Mere DBAs'	,	'Jason'	,	'Brimhall'	,	'Intermediate'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'Scaling with SQL Server Service Broker'	,	'Hilary'	,	'Cotter'	,	'Advanced'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'Scaling with SQL Server Service Broker'	,	'Hilary'	,	'Cotter'	,	'Advanced'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'Self-Service Data Integration with Power Query'	,	'Stéphane'	,	'Fréchette'	,	'Beginner'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'Shortcuts to Building SSIS in .Net'	,	'Paul'	,	'Rizza'	,	'Beginner'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'So You Want To Be A Consultant?'	,	'Allan'	,	'Hirt'	,	'Beginner'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'SQL anti patterns'	,	'Kennie'	,	'Pontoppidan'	,	'Advanced'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'SQL Server 2012/2014 Columnstore index'	,	'Kevin'	,	'Goff'	,	'Intermediate'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'SQL Server 2012/2014 Performance Tuning All Up'	,	'George'	,	'Walters'	,	'Intermediate'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'SQL Server 2014 Data Access Layers'	,	'Steve'	,	'Simon'	,	'Intermediate'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'SQL Server 2014 New Features'	,	'George'	,	'Walters'	,	'Intermediate'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'SQL Server AlwaysOn Availability Groups'	,	'George'	,	'Walters'	,	'Beginner'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'SQL Server and the Cloud'	,	'David'	,	'Peter Hansen'	,	'Beginner'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'SQL Server Compression and what it can do for you'	,	'Jason'	,	'Brimhall'	,	'Advanced'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'SQL Server Reporting Services 2014 on Steroids!!'	,	'Steve'	,	'Simon'	,	'Intermediate'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'SQL Server Reporting Services Best Practices'	,	'Steve'	,	'Simon'	,	'Intermediate'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'SQL Server Reporting Services, attendees choose'	,	'Kevin'	,	'Goff'	,	'Intermediate'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'SQL Server Storage Engine under the hood'	,	'Thomas'	,	'Grohser'	,	'Intermediate'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'SQL Server Storage internals: Looking under the hood.'	,	'Brandon'	,	'Leach'	,	'Advanced'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'SSIS 2014 Data Flow Tuning Tips and Tricks'	,	'Andy'	,	'Leonard'	,	'Beginner'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'Standalone to High-Availability Clusters over Lunch—with Time to Spare'	,	'Carl'	,	'Berglund'	,	'Intermediate'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'Stress testing SQL Server'	,	'Hilary'	,	'Cotter'	,	'Advanced'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'Table partitioning for Azure SQL Databases'	,	'John'	,	'Miner'	,	'Beginner'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'Testing'	,	'Melissa'	,	'Riley'	,	'Beginner'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'The future of the data professional'	,	'Adam'	,	'Jorgensen'	,	'Beginner'	,	'Kiyv'	);
        INSERT INTO TemporaryTable VALUES (	'The Quest for the Golden Record:MDM Best Practices'	,	'Dennis'	,	'Messina'	,	'Beginner'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'The Quest to Find Bad Data With Data Profiling'	,	'Richie'	,	'Rump'	,	'Intermediate'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'The Spy Who Loathed Me - An Intro to SQL Security'	,	'Chris'	,	'Bell'	,	'Beginner'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'Tired of the CRUD? Automate it!'	,	'Jack'	,	'Corbett'	,	'Intermediate'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'Top 5 Ways to Improve Your triggers'	,	'Aaron'	,	'Bertrand'	,	'Intermediate'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'Tricks that have saved my bacon'	,	'Greg'	,	'Moore'	,	'Beginner'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'T-SQL : Bad Habits & Best Practices'	,	'Aaron'	,	'Bertrand'	,	'Beginner'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'T-SQL for Application Developers - Attendees chose'	,	'Kevin'	,	'Goff'	,	'Intermediate'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'Tune Queries By Fixing Bad Parameter Sniffing'	,	'Grant'	,	'Fritchey'	,	'Intermediate'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'Using Extended Events in SQL Server'	,	'Jason'	,	'Brimhall'	,	'Advanced'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'Watch Brent Tune Queries'	,	'Brent'	,	'Ozar'	,	'Intermediate'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'What every SQL Server DBA needs to know about Windows Server 10 Technical Preview'	,	'David'	,	'Bermingham'	,	'Intermediate'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'What exactly is big data and why should I care?'	,	'James'	,	'Serra'	,	'Beginner'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'What is it like to work for Microsoft?'	,	'James'	,	'Serra'	,	'Beginner'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'What’s new in SQL Server Integration Services 2012'	,	'Kevin'	,	'Goff'	,	'Intermediate'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'Why do we shun using tools for DBA job?'	,	'Paresh'	,	'Motiwala'	,	'Intermediate'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'Why OLAP? Building SSAS cubes and benefits of OLAP'	,	'Kevin'	,	'Goff'	,	'Intermediate'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES (	'You''re Doing It Wrong!!'	,	'Mike'	,	'Walsh'	,	'Intermediate'	,	'Budapest'	);
        INSERT INTO TemporaryTable VALUES ('Raffle', 'SQLSaturday', '364', 'Non-Technical', 'Kiyv');
        INSERT INTO TemporaryTable VALUES ('Registrations', 'SQLSaturday', '364', 'Non-Technical', 'Kiyv');


      END TRY
      BEGIN CATCH
        SELECT ERROR_MESSAGE() AS ErrorMessage;
      END CATCH
    END